---
addons: { apt: { packages: [ libgtk2.0-dev, txt2tags ] } }
language: c
script:
  - mkdir _build _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
  - make VERBOSE=1
  - ctest $CTESTFLAGS
  - make install
jobs:
  include:
    - env: [ ACTION=omnilint ]
      language: generic
      sudo: required # docker
      services: [ docker ]
      addons: {}
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    - env: [ ACTION=gcc ]
      compiler: gcc
    - env: [ ACTION=clang ]
      compiler: clang
