.TH "xselman" 1 "" ""


.SH NAME

.P
xselman \- X selection management.

.SH SYNOPSIS

.P
\fBxselman\fR

.SH DESCRIPTION

.P
\fBxselman\fR is a program that manages X selections.

.P
For now, that means that it synchronizes the primary selection with the
clipboard (and vice\-versa).

.SH OPTIONS

.P
\fB\-h\fR Help.

.SH AUTHOR

.P
Written by Leandro Penz

.SH REPORTING BUGS

.P
https://github.com/lpenz/xselman/issues/new

.SH COPYRIGHT

.P
Copyright (C) 2010 Leandro Lisboa Penz <lpenz@lpenz.org>

.SH SEE ALSO

.P
\fBxclipboard\fR(1), \fBxclip\fR(1), \fBX\fR(7)
